name: dotnet-build

on: 
  push:
  schedule:
    - cron: '0 * * * *' # Execução a cada hora

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar o .NET SDK 8.0.x
        run: |
          wget https://dot.net/v1/dotnet-install.sh -O dotnet-install.sh
          chmod +x dotnet-install.sh
          ./dotnet-install.sh --channel 8.0
          echo "$HOME/.dotnet" >> $GITHUB_PATH

      - name: Exibir versão instalada
        run: ~/.dotnet/dotnet --version

      - name: Restaurar pacotes
        run: dotnet restore **/*.csproj

      - name: Build do projeto
        run: dotnet build **/*.csproj --no-restore --configuration Release